### ISSUE TITLE
Flatpak wants to remove dependencies of this package

### ISSUE THREAD

**Issue by nightuser** [flathub/org.gtk.Gtk3theme.Plata#1]
Hey!

I use this theme with flatpak and it works correctly. However, when I run `flatpak --user uninstall --unused` it suggests me to remove `org.freedesktop.Platform* 1.6` packages, but asks to install them again during `flatpak --user update`.

I don't know whether it's the right place to post this issue since it might be a more general problem.

**Comment by TingPing** [comment]
Please report this against https://github.com/flatpak/flatpak

The real issue is that this theme shouldn't pull in *any* runtime.

**Comment by TingPing** [comment]
I reported this: https://github.com/flatpak/flatpak/issues/3173
